trigger:
- 'main'

variables:
  buildConfiguration: 'Release'
  linkedinGamesRankingRepository: 'julescrevola/linkedin-games'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'

stages:
- stage: Build
  displayName: Build the containers
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push the linkedin-games image to Docker Hub
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(linkedinGamesRankingRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'service-connection-docker'
        tags: |
          $(tag)

    - publish: '$(Build.SourcesDirectory)/deployment.yaml'
      artifact: manifests

- stage: Deploy
  displayName: Deploy the containers
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'linkedin_games_ranking'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests

          - script: |
              mkdir -p .streamlit
              cat <<EOF > .streamlit/secrets.toml
              SUPABASE_URL = "$(SUPABASE_URL)"
              SUPABASE_KEY = "$(SUPABASE_KEY)"
              EOF
            displayName: Create secrets.toml

          - task: AzureCLI@2
            displayName: Create Kubernetes secret
            inputs:
              azureSubscription: service-connection-linkedin-games-ranking
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials \
                  --resource-group rg-linkedin_games \
                  --name linkedin_games_ranking \
                  --overwrite-existing

                kubectl create secret generic streamlit-secrets \
                  --from-file=secrets.toml=.streamlit/secrets.toml \
                  --dry-run=client -o yaml | kubectl apply -f -

          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              connectionType: azureResourceManager
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'service-connection-docker'
              azureSubscriptionConnection: 'service-connection-linkedin-games-ranking'
              azureResourceGroup: 'rg-linkedin_games'
              kubernetesCluster: 'linkedin_games_ranking'
              namespace: 'default'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              connectionType: azureResourceManager
              azureSubscriptionConnection: 'service-connection-linkedin-games-ranking'
              azureResourceGroup: 'rg-linkedin_games'
              kubernetesCluster: 'linkedin_games_ranking'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(RegistryName)/$(linkedinGamesRankingRepository):$(tag)
